name: venv
channels:
  - defaults
  - conda-forge
  - anaconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.10
  - opencv
  - numpy
  - tensorflow
  - tensorflow-base
  - uvicorn
  - pip:
      - annotated-types
      - anyio
      - click
      - colorama
      - dnspython
      - email-validator
      - exceptiongroup
      - fastapi
      - fastapi-cli
      - h11
      - httpcore
      - httptools
      - httpx
      - idna
      - jinja2
      - markdown-it-py
      - mdurl
      - numpy
      - pydantic
      - pydantic-core
      - python-dotenv
      - python-multipart
      - pyyaml
      - rich
      - rich-toolkit
      - shellingham
      - sniffio
      - starlette
      - typer
      - typing-extensions
      - typing-inspection
      - watchfiles
      - websockets
